<?php

ini_set('include_path', ini_get('include_path')
        . PATH_SEPARATOR
        . './'
        . PATH_SEPARATOR
        . '../'
        . PATH_SEPARATOR
        . '../../'
        . PATH_SEPARATOR
);

require_once 'classes/EventbriteICS.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-22 at 11:19:44.
 */
class EventbriteICSTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EventbriteICS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EventbriteICS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    /**
     * @covers EventbriteICS::readEventbrite
     */
    public function testReadEventbrite() {
        // This is what the default is when there is no API key ...
        $expected = "BEGIN:VCALENDAR" . CRLF
                . "VERSION:2.0" . CRLF
                . "METHOD:PUBLISH" . CRLF
                . "PRODID:-//PMI SFBAC//PMICalendar//EN" . CRLF
                . "CALSCALE:GREGORIAN" . CRLF
                . "X-WR-CALNAME:PMI-SFBAC Eventbrite Calendar" . CRLF
                . "X-WR-TIMEZONE:America/Los_Angeles" . CRLF
                . "X-WR-CALDESC:This is the PMI-SFBAC Eventbrite Calendar" . CRLF
                . "BEGIN:VTIMEZONE" . CRLF
                . "TZID:America/Los_Angeles" . CRLF
                . "X-LIC-LOCATION:America/Los_Angeles" . CRLF
                . "BEGIN:DAYLIGHT" . CRLF
                . "TZOFFSETFROM:-0800" . CRLF
                . "TZOFFSETTO:-0700" . CRLF
                . "TZNAME:PDT" . CRLF
                . "DTSTART:19700308T020000" . CRLF
                . "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU" . CRLF
                . "END:DAYLIGHT" . CRLF
                . "BEGIN:STANDARD" . CRLF
                . "TZOFFSETFROM:-0700" . CRLF
                . "TZOFFSETTO:-0800" . CRLF
                . "TZNAME:PST" . CRLF
                . "DTSTART:19701101T020000" . CRLF
                . "RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU" . CRLF
                . "END:STANDARD" . CRLF
                . "END:VTIMEZONE" . CRLF
                . "BEGIN:VEVENT" . CRLF
                // This should be the URL of the calendar
                . "URL;VALUE=URI:http://www.pmi-sfbac.org/" . CRLF
                // These next two need to be updated to be for today ...
                . "DTSTART;TZID=America/Los_Angeles:20121122T120000" . CRLF
                . "DTEND;TZID=America/Los_Angeles:20121122T163000" . CRLF
                . "SUMMARY:No rows found" . CRLF
                . "END:VEVENT" . CRLF
                . "END:VCALENDAR";
        $result = $this->object->readEventbrite();
        $this->assertEquals($expected, $result, 'Problem with iCal data');
    }

    public function testReadEventbriteWithKey() {
        $this->object->setConfig(array('app_key' => 'V6KZF7NVIL7KPHPD6H',
            'user_key' => '131639172020232618306'));
        $expected = "BEGIN:VCALENDAR" . CRLF
                . "VERSION:2.0" . CRLF
                . "METHOD:PUBLISH" . CRLF
                . "PRODID:-//PMI SFBAC//PMICalendar//EN" . CRLF
                . "CALSCALE:GREGORIAN" . CRLF
                . "X-WR-CALNAME:PMI-SFBAC Eventbrite Calendar" . CRLF
                . "X-WR-TIMEZONE:America/Los_Angeles" . CRLF
                . "X-WR-CALDESC:This is the PMI-SFBAC Eventbrite Calendar" . CRLF
                . "BEGIN:VTIMEZONE" . CRLF
                . "TZID:America/Los_Angeles" . CRLF
                . "X-LIC-LOCATION:America/Los_Angeles" . CRLF
                . "BEGIN:DAYLIGHT" . CRLF
                . "TZOFFSETFROM:-0800" . CRLF
                . "TZOFFSETTO:-0700" . CRLF
                . "TZNAME:PDT" . CRLF
                . "DTSTART:19700308T020000" . CRLF
                . "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU" . CRLF
                . "END:DAYLIGHT" . CRLF
                . "BEGIN:STANDARD" . CRLF
                . "TZOFFSETFROM:-0700" . CRLF
                . "TZOFFSETTO:-0800" . CRLF
                . "TZNAME:PST" . CRLF
                . "DTSTART:19701101T020000" . CRLF
                . "RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU" . CRLF
                . "END:STANDARD" . CRLF
                . "END:VTIMEZONE" . CRLF
                . "BEGIN:VEVENT" . CRLF
                ;
        $result = $this->object->readEventbrite();
        $this->assertContains($expected, $result, 'Problem with iCal data for PMI feed');
    }

    /**
     * @covers EventbriteICS::sendICS
     * @todo   Implement testSendICS().
     */
    public function testSendICS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
